// Container file for dummy headlines

export const placeholder_headlines = [
    "Notable earnings after Thursday's close",
    'Intersil Beats 1Q Earnings, Revs Lag - Analyst Blog',
    'Brunswick (BC) Plans To Spin-Off Fitness Business - Slideshow',
    "Consolidated Communications (CNSL) Q2 Earnings: What's Up?",
    'Day Two Keynote Speaker, Charlie Riedl with CLNG, Announced for EnerCom Dallas Energy ...',
    'EQT Rubbishes JANA Claims on Rice Energy Buyout Synergies',
    'Retailers look for government help for shipping crisis',
    'Sempra Energy Donates To Fisher House Foundation As Part Of Commitment To Veteran Causes',
    'Still Bullish on BioMarin, Lexicon Pharma',
    'MoneyGram Shares Jump 50% As Western Union Reportedly Looks For Acquisition',
    "Domino's And Papa John's Face Major Threat As Pizza Industry Is Set To Change",
    'GameStop near Support',
    'Apple: A Top Fidelity Manager Sticks By The Stock',
    'Ex-Dividend Stocks: Intel, Citigroup',
    'Border tax seen as a profit headwind for major retailers',
    'REITs: Something to Build On - Zacks Analyst Interviews',
    "What's Next For Oil?", 
    'Paramount to Trim Jobs - Analyst Blog',
    'Investors Walking Dead',
    'ROSEN, A LEADING LAW FIRM, Reminds International Flavors & Fragrances Inc. ...',
    'Crown Castle declares $0.885 dividend',
    'Amazon Now Charging Sales Taxes In Three More States',
    'BlackRock threatens buyers strike for Illinois debt',
    'Stocks Showing Improved Relative Strength: BankUnited',
    '10 Stocks Delivering Good News With Higher Dividends',
    'Swiss National Bank Ready To Buy Much More Tech Stocks To Weaken The Franc',
    'Xcel, Duke Boast Yields And Strength',
    'Omeros misses by $0.01, misses on revenue',
    "HP Introduces New 'D Printing Subscriptions, Services, and Partnerships to Accelerate ...",
    'Robo Advice: Why More Human Advisors Are Embracing It'
]
